name: flutterappapptest
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_rounded_progress_bar: ^0.1.2
  flutter_animation_progress_bar: ^1.0.0
  gradient_text: ^1.0.2
  liquid_progress_indicator: ^0.3.2
  step_progress_indicator: ^0.2.1+4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf

    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
